### ISSUE TITLE
React production docker image

### ISSUE THREAD

**Issue by zerbinidamata** [ZKDevs/dockerfiles#15]

**Comment by Arnab7456** [comment]
can you elaborate it more , it's help me to contribute

**Comment by zerbinidamata** [comment]
Sure thing. We basically want a docker image that is ready to be extended by an application and be executed in production. Keep in mind that the idea is to have a general image, so it should have only configuration needed to run it in production. We can have multiple image versions with different packages, monitoring, compressing system and whatever. It just needs to be clear.
